services:
  # backend:
  #   build: .
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     - LOGFIRE_TOKEN=$LOGFIRE_TOKEN
  #     - LOGLEVEL=$LOGLEVEL
  #     - OPENROUTESERVICE_KEY=$OPENROUTESERVICE_KEY
  #     - POSTGRES_HOST=$POSTGRES_HOST
  #     - ADDOK_HOST=$ADDOK_HOST
  #     - POSTGRES_DB=$POSTGRES_DB
  #     - POSTGRES_USER=$POSTGRES_USER
  #     - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  #     - API_PATH=$API_PATH
  #   volumes:
  #     - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/data:/code
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`) && PathPrefix(`$API_PATH`)"
  #     - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
  #     - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
  #     - "traefik.http.routers.$COMPOSE_PROJECT_NAME.middlewares=$COMPOSE_PROJECT_NAME-stripprefix@docker"
  #     - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=3566"
  #     - "traefik.http.middlewares.$COMPOSE_PROJECT_NAME-stripprefix.stripprefix.prefixes=$API_PATH"
  #     - "traefik.http.middlewares.$COMPOSE_PROJECT_NAME-stripprefix.stripprefix.forceSlash=false"
  #     - "homepage.group=$HOME_GROUP"
  #     - "homepage.name=$HOME_NAME"
  #     - "homepage.icon=$HOME_ICON"
  #     - "homepage.href=https://${HOST}${API_PATH}/docs"
  #     - "homepage.description=$HOME_DESCRIPTION"

  db:
    image: postgis/postgis
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/db:/var/lib/postgresql/data
    environment:
      TZ: $TZ
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
