services:
  web:
    build: .
    volumes:
      # - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/data:/data
      - /home/yann/Downloads/xandikos_data:/data
    environment:
      - USER=$USER
      - PASSWORD=$PASSWORD
      - LOGFIRE_TOKEN=$LOGFIRE_TOKEN
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=8000"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://$HOST"
      - "homepage.description=$HOME_DESCRIPTION"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
