services:
  web:
    build: .
    volumes:
      # - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/data:/code/data
      - /home/yann/repos/fireset/data:/code/data
    environment:
      - FIRESET_USER=$FIRESET_USER
      - FIRESET_PASSWORD=$FIRESET_PASSWORD
      - DATABASE_URI=$DATABASE_URI
      - PHANTOMBUSTER_KEY=$PHANTOMBUSTER_KEY
      - PHANTOMBUSTER_LISTID=$PHANTOMBUSTER_LISTID
      - LOGFIRE_TOKEN=$LOGFIRE_TOKEN
      - LOGLEVEL=$LOGLEVEL
      - PUSHOVER_APP_TOKEN=$PUSHOVER_APP_TOKEN
      - PUSHOVER_USER_KEY=$PUSHOVER_USER_KEY
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=3665"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://$HOST"
      - "homepage.description=$HOME_DESCRIPTION"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
